// Code generated by "stringer -type=ItemType"; DO NOT EDIT.

package zappaclang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[itemError-0]
	_ = x[itemEOF-1]
	_ = x[itemEquals-2]
	_ = x[itemSpace-3]
	_ = x[itemLParen-4]
	_ = x[itemRParen-5]
	_ = x[itemNumber-6]
	_ = x[itemVariable-7]
	_ = x[itemAdd-8]
	_ = x[itemSub-9]
	_ = x[itemMult-10]
	_ = x[itemExp-11]
	_ = x[itemDiv-12]
	_ = x[itemFdiv-13]
	_ = x[itemAnd-14]
	_ = x[itemOr-15]
	_ = x[itemXor-16]
	_ = x[itemInv-17]
	_ = x[itemMod-18]
	_ = x[itemLShift-19]
	_ = x[itemRShift-20]
	_ = x[itemText-21]
	_ = x[itemAbs-22]
	_ = x[itemSave-23]
	_ = x[itemLoad-24]
	_ = x[itemDec-25]
	_ = x[itemHex-26]
	_ = x[itemBin-27]
	_ = x[itemOct-28]
	_ = x[itemClear-29]
}

const _ItemType_name = "itemErroritemEOFitemEqualsitemSpaceitemLParenitemRParenitemNumberitemVariableitemAdditemSubitemMultitemExpitemDivitemFdivitemAnditemOritemXoritemInvitemModitemLShiftitemRShiftitemTextitemAbsitemSaveitemLoaditemDecitemHexitemBinitemOctitemClear"

var _ItemType_index = [...]uint8{0, 9, 16, 26, 35, 45, 55, 65, 77, 84, 91, 99, 106, 113, 121, 128, 134, 141, 148, 155, 165, 175, 183, 190, 198, 206, 213, 220, 227, 234, 243}

func (i ItemType) String() string {
	if i < 0 || i >= ItemType(len(_ItemType_index)-1) {
		return "ItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
