// Code generated by "stringer -type=NumberSystem"; DO NOT EDIT.

package zappaclang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dec-0]
	_ = x[Hex-1]
	_ = x[Bin-2]
	_ = x[Oct-3]
}

const _NumberSystem_name = "DecHexBinOct"

var _NumberSystem_index = [...]uint8{0, 3, 6, 9, 12}

func (i NumberSystem) String() string {
	if i < 0 || i >= NumberSystem(len(_NumberSystem_index)-1) {
		return "NumberSystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NumberSystem_name[_NumberSystem_index[i]:_NumberSystem_index[i+1]]
}
